import { Roboto, Montserrat } from 'next/font/google';
import "./globals.css";
import { Providers } from './providers';


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

const montserrat = Montserrat({
  variable: "--font-montserrant",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${montserrat.variable} antialiased`}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
